### ISSUE TITLE
Q2A 1.8: Uncaught Error: Call to undefined function donut_lang()

### ISSUE THREAD

**Issue by rklec** [amiyasahu/Donut#124]
Is this theme compatible with Q2A v1.8?

Because in my case directly after installing and switching to thge theme in the setings (both mobile theme and "usual" theme) I get an error:
```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function donut_lang() in /var/www/html/q2a/qa-theme/Donut/templates/user-loggedin-drop-down.php:38
192.168.16.3 -  02/Oct/2020:11:54:15 +0000 "GET /index.php" 200
Stack trace:
#0 /var/www/html/q2a/qa-theme/Donut/qa-donut-layer.php(674): require_once()
#1 /var/www/html/q2a/qa-theme/Donut/qa-donut-layer.php(543): qa_html_theme->donut_user_drop_down()
#2 /var/www/html/q2a/qa-theme/Donut/qa-donut-layer.php(507): qa_html_theme->donut_nav_bar(Array)
#3 /var/www/html/q2a/qa-include/qa-theme-base.php(389): qa_html_theme->body_header()
#4 /var/www/html/q2a/qa-include/qa-theme-base.php(270): qa_html_theme_base->body()
#5 /var/www/html/q2a/qa-include/app/page.php(359): qa_html_theme_base->html()
#6 /var/www/html/q2a/qa-include/qa-page.php(53): qa_output_content(Array)
#7 /var/www/html/q2a/qa-include/qa-index.php(188): require('/var/www/html/q...')
#8 /var/www/html/q2a/index.php(27): require('/var/www/html/q...')
#9 {main}
  thrown in /var/www/html/q2a/qa-theme/Donut/templates/user-loggedin-drop-down.php on line 38
```

**Comment by arjunsuresh1987** [comment]
Have you put "donut-admin" folder under qa-plugins?

**Comment by rklec** [comment]
Sorry, thanks, indeed this was the issue. It was accidentially a subfolder.
Moving that fixed the issue.
